url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Qichunren blog" # the name of your site, e.g. ACME Corp.
timezone: "China/Shanghai"

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md
  - package.json
  - package-lock.json
  - tailwind.config.js
  - yarn.lock
  - assets/css/application.tailwind.css

collections:
  dev_tips:
    output: true
